[[worlds]]
id = 0
name = "Scania"
channels = 1
flag = 0
event_message = "Scania!"
recommended = "Welcome to Scania!"
exp_rate = 10
meso_rate = 10
drop_rate = 10
boss_drop_rate = 10
quest_rate = 5
fishing_rate = 10
travel_rate = 10

[[worlds]]
id = 1
name = "Bera"
channels = 1
flag = 0
event_message = "Bera!"
recommended = "Welcome to Bera!"
exp_rate = 10
meso_rate = 10
drop_rate = 10
boss_drop_rate = 10
quest_rate = 5
fishing_rate = 10
travel_rate = 10